### ISSUE TITLE
douyin订阅出错

### ISSUE THREAD

**Issue by Arukassss** [nfe-w/aio-dynamic-push#10]
配置文件，签名服务器是本地部署的
  - name: 抖音
    enable: true
    type: douyin
    intervals_second: 30
    begin_time: "00:00"
    end_time: "23:59"
    target_push_name_list:
      - 推送通道_飞书自建应用
    enable_dynamic_check: true
    # 签名服务器url，参考 https://github.com/coder-fly/douyin-signature
    signature_server_url: http://127.0.0.1:7878
    # 用户名列表，必填（接口现在不返回作者信息了，重新获取还挺麻烦的，自己填上凑合用先）
    username_list:
      - 罗塞菈Rosella
      - 俄洛伊小迷妹ee
      - 聆鹿歌
      - 莉莉丝Channel
      - 七海Nana7mi
      - 阿梓从小就很可爱
    # 作者sec_uid列表，参考 https://www.douyin.com/user/MS4wLjABAAAA5ZrIrbgva_HMeHuNn64goOD2XYnk4ItSypgRHlbSh1c
    sec_uid_list:
      - MS4wLjABAAAAk3VFJyQADFrzT732DfKSRyEradMPVp1LsNghWIvNSIhR7uF1QpA8fSejh-2zr-gy
      - MS4wLjABAAAAshurg6jJDz_utAtWyvfZVVkDQ_EvxYcnoRK_3iUcNDE
      - MS4wLjABAAAAN_9tRMTAfxWGCF_k4-d1m6FewWD7GR6ZGlO7T8xGmt0
      - MS4wLjABAAAAGelXEDvmBIr6QAkY20oy7x5DSMSGSwBl-yJ8J8dIfQB99yURGVGrGaxBs-mJUA5t
      - MS4wLjABAAAAGeiluJjizroSmPhcNdlsS0b7M0rxi5ygfrtqdByE0FCYi__j0fS_E52uGaF7ujpn
      - MS4wLjABAAAAGZt3gsaErTrQeUhM2_QXpHeHUcsd8A_McEnTcedPJBSV2a1z0L9sNloJ4r0IhnFl
    enable_living_check: false
    # 抖音号列表，用于检测开播状态，如果不开启直播检测可以不填，暂不支持纯数字的抖音号
    douyin_id_list:
      - Kuangyiii
      - Nana7mi0715
报错如下
2024-05-07 22:56:52,518 - 2825883-MainThread -      query_douyin.py[line: 37] - ERROR: 【抖音-查询任务-抖音】出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/aio-dynamic-push-master/query_task/query_douyin.py", line 32, in query
    self.query_dynamic(self.username_list[i], self.sec_uid_list[i])
  File "/home/aio-dynamic-push-master/query_task/query_douyin.py", line 54, in query_dynamic
    result = json.loads(str(response.content, "utf-8"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Arukassss** [comment]
> 抖音的视频检测好像挂了，老接口被ban了，暂时不知道怎么修😢

那微博可以发文字和图片吗，现在只会推送文字

**Comment by nfe-w** [comment]
微博一直可以的图文呀
<img width="485" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/49c19f09-cf3a-4328-9ae9-68adfe796ab1">

**Comment by Arukassss** [comment]
> 微博一直可以图文呀 <img alt="image" width="485" src="https://private-user-images.githubusercontent.com/41944640/328575173-49c19f09-cf3a-4328-9ae9-68adfe796ab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTQ1NzgsIm5iZiI6MTcxNTA5NDI3OCwicGF0aCI6Ii80MTk0NDY0MC8zMjg1NzUxNzMtNDljMTlmMDktY2YzYS00MzI4LTlhZTktNjhhZGZlNzk2YWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE1MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDc2ZDY1MDIzYTFhNWRiZGQ2ZWMwNGE2OWQ4NzRiMTBiODczN2VhNzgzMWZjYzkzNzZhYzMxOTY4NzQ1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OmMghuRtNB2WLVDOYJWLcKW3Wt8up5UZBY1aK-u-yOY">

![image](https://github.com/nfe-w/aio-dynamic-push/assets/89686441/47370587-583d-42e1-9c74-7628550b6912)
![image](https://github.com/nfe-w/aio-dynamic-push/assets/89686441/d5ff2441-3c78-4165-945a-8d84b0730c2f)
我推到飞书应用的收不到微博的图片，但是B站的动态和直播是能收到图片的

**Comment by nfe-w** [comment]
9846ac2219ed7213bcb6a681edc5c9071a308e2b

尝试修复了一下，因为飞书的图片是需要先下载到本地再上传到飞书，其他的推送通道则是直接传参图片URL

在下载图片时，不知道为什么请求头只要包含了 User-Agent 就会403，即使加了 referer 或 Host 也不行，反而是不携带任何 headers 不会被拦截，这样改了一下，现在已经构建完毕可以拉镜像试试看

我平时主要在用 企微应用 和 钉钉bot 推送，没在使用飞书，可能没法完善地测试
