### ISSUE TITLE
pc端xhs图片缺失，但手机端正常，同一网络环境

### ISSUE THREAD

**Issue by Looper0331** [nfe-w/aio-dynamic-push#11]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/2f9be5ca-13fe-4946-9be3-9eda4daa8490)

![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/13fde23c-073d-41ac-9887-3e4123027f79)

![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/01bd2878-3d92-4f09-b984-606a4008f3de)

**Comment by nfe-w** [comment]
我这里测试是可以的，手机PC均正常，可以再观察看看

<img width="324" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/89a4c037-40ed-45c1-8c03-1283ce1e0d17">

**Comment by Looper0331** [comment]
> 我这里测试是可以的，手机PC均正常，可以再观察看看
> 
> <img alt="image" width="324" src="https://private-user-images.githubusercontent.com/41944640/328770479-89a4c037-40ed-45c1-8c03-1283ce1e0d17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDgxMzIsIm5iZiI6MTcxNTE0NzgzMiwicGF0aCI6Ii80MTk0NDY0MC8zMjg3NzA0NzktODlhNGMwMzctNDBlZC00NWMxLThjMDMtMTI4M2NlMWUwZDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA1NTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NjZjODhjM2YwNmE1ZmZhYjJlM2VmNmZiYmFkZDJhOWIzZjkyYmE0Y2E5MTE4ZTc0ZDUyOGJmN2RiOTdjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tLwpsfUJveDdFve2UAYO2y_-TYedSBJ8UgNSVqfiI4Y">

ok，我再测试测试，换个群机器人看看

**Comment by Looper0331** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/bd3a66c6-e733-4b4e-8ec0-d843a0e9fa0d)

我感觉是系统不同的问题，下面有图片的是我调的公众号的订阅图，是正常的。我突然发现你发的那个截图的MACBook的，而且我手机是iOS的，但我这边同事的windows电脑也是无法显示。 感觉只会是系统兼容的问题，方便的话可以测试看看

**Comment by nfe-w** [comment]
好的，稍晚些我在Windows上试试看

**Comment by nfe-w** [comment]
1194fcf9928873c61b6062c5e65f967f844a125a
已修复，原因是：
小红书默认图片URL格式为： `http://sns-webpic-qc.xhscdn.com/202405082113/5af2509bcd86ed9a9f0c509923b45bd3/1040g008312hel6pb76005pb7vg36aa26e4mkoh8!nc_n_webp_mw_1` Windows企微不知道为什么对这种格式兼容的不好
我替换成了这种格式： `https://ci.xiaohongshu.com/1040g008312hel6pb76005pb7vg36aa26e4mkoh8?imageView2/2/w/500/format/jpg` 现在应该可以了

**Comment by Looper0331** [comment]
> [1194fcf](https://github.com/nfe-w/aio-dynamic-push/commit/1194fcf9928873c61b6062c5e65f967f844a125a) 已修复，原因是： 小红书默认图片URL格式为： `http://sns-webpic-qc.xhscdn.com/202405082113/5af2509bcd86ed9a9f0c509923b45bd3/1040g008312hel6pb76005pb7vg36aa26e4mkoh8!nc_n_webp_mw_1` Windows企微不知道为什么对这种格式兼容的不好 我替换成了这种格式： `https://ci.xiaohongshu.com/1040g008312hel6pb76005pb7vg36aa26e4mkoh8?imageView2/2/w/500/format/jpg` 现在应该可以了

好的，我自己采用的就是带jpg或png后缀的链接格式。确实是这个原因，官方有说明：https://developers.weixin.qq.com/community/enterprisewechat/doc/000e2e68f78a68b8514b3862756800
那我重新拉取下镜像，感谢了~
