### ISSUE TITLE
xhs-企业机器人 图片还是无法显示

### ISSUE THREAD

**Issue by Looper0331** [nfe-w/aio-dynamic-push#12]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/2c74ae95-d201-4a39-a36a-c2a1228f7476)

重新拉去了镜像，这下电脑和手机都不显示了。。。是不是pic_url字符串拼接有误。。。肯能还得麻烦检查下~

之前问题官方说明：https://developers.weixin.qq.com/community/enterprisewechat/doc/000e2e68f78a68b8514b3862756800

**Comment by nfe-w** [comment]
没理由呀。。
<img width="329" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/919f886d-8d0b-4fde-b83b-95cb708f8ed3">
<img width="329" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/eee443b9-beac-4a1f-a098-8ff47a8fedfd">

**Comment by Looper0331** [comment]
debug后是有重新构建镜像吗，我是刚刚重新拉去镜像的，配置文件没变动。。

**Comment by nfe-w** [comment]
代码提交后镜像是自动构建的，而且我换安卓手机看了一眼，也是有图片的，你是用那个profile_id试的？
https://github.com/nfe-w/aio-dynamic-push/actions/runs/9002702758
https://hub.docker.com/repository/docker/nfew/aio-dynamic-push/tags

**Comment by Looper0331** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/5dcda163-dbc0-4917-a232-8568f1a035cf)

镜像你看到了是改过的，这个地方，后缀确定是".jpg"吗。。。

**Comment by Looper0331** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/420f0f94-7a62-452f-a868-7ade0f104444)

我自己的号测试，5d7b9ef80000000001000ad5

**Comment by nfe-w** [comment]
https://ci.xiaohongshu.com/{pic_id}?imageView2/2/w/500/format/jpg
是七牛图片处理器的用法

**Comment by Looper0331** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/b91523c6-6c0c-4951-a5c7-e01cd8d74a4b)

**Comment by Looper0331** [comment]
这种url应该不行，必须之 ".jpg"或".png" 后缀的直链才行

**Comment by nfe-w** [comment]
问题是小红书拿不到.jpg或.png结尾的图片链接

**Comment by nfe-w** [comment]
你这个图片url确实不兼容七牛图片处理的url格式（不太清楚原因），我还是把刚才的提交回滚吧，起码之前 安卓、iPhone、mac 是正常的

**Comment by Looper0331** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/379d92c2-2b07-425e-b662-86a6828daf25)

![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/5d439659-a067-464f-abc0-fb198e1f049f)

不对，我错了，我看了我微信获取的url，是这样的，但是浏览器可以直接打开

**Comment by Looper0331** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/63d50291-04cc-4f3c-88b8-8f0c4690a786)

看了下，xhs图片需要触发下载后获取base64码再去转换解码

**Comment by nfe-w** [comment]
但企微bot对于 "msgtype": "news" 只接收图片url， 也不能先下载再上传到哪儿

其实我感觉这是企业微信的bug，除了Windows的企微，其他都正常支持xhs原生的pic_url，而且钉钉飞书也正常支持

**Comment by Looper0331** [comment]
> 但企微bot对于 "msgtype": "news" 只接收图片url， 也不能先下载再上传到哪儿
> 
> 其实我感觉这是企业微信的bug，除了Windows的企微，其他都正常支持xhs原生的pic_url，而且钉钉飞书也正常支持

哈哈，明天我问下企微客户试试，真是发现大瓜了。。我也再想想有没有其他转换的办法，谢谢了哈，辛苦辛苦
