### ISSUE TITLE
webhook传递参数增加

### ISSUE THREAD

**Issue by Arukassss** [nfe-w/aio-dynamic-push#13]
对于其他推送方式要符合规范，所以不好修改传递参数。但是对于webhook传递的参数一般都是收到之后进行处理再使用，仅仅是title和content两个参数缺少太多原始信息，可否把
uname: up主名字 
dynamic_id: 动态id 
content: 动态内容
pic_url: 动态图片 
dynamic_type: 动态类型 
dynamic_time: 动态发送时间 
title_msg: 推送标题 
这些参数全部发送。
还请增加一个投稿时的视频链接，即module_dynamic["major"]["archive"]["jump_url"]，以及一起加入到webhook的参数当中。
如果其他推送方式也能在content的下方添加视频链接就更好了。（可有可无）

**Comment by nfe-w** [comment]
传递参数增加这个没问题👌🏻我下班后加一下

但在其他推送方式的content里添加视频链接感觉不是很方便，好多推送方式是限制content长度的，目前对动态本身的文字都已经限制了100个字

**Comment by Arukassss** [comment]
> 传递参数增加这个没问题👌🏻我下班后加一下
> 
> 但在其他推送方式的content里添加视频链接感觉不是很方便，好多推送方式是限制content长度的，目前对动态本身的文字都已经限制了100个字

那就webhook添加就好。我是推到飞书应用，动态有多张图片的时候也只会发送第一张，在webhook里面可否可以把动态所有的链接都加进去

**Comment by Arukassss** [comment]
> 对于 **POST** 方式的 Webhook ，我的设想是将 `该条动态的原始数据` 放在 body 里一并推送

可以的，反正没参数数量限制，参数越多对后端拿数据更方便

**Comment by nfe-w** [comment]
已添加并且构建完毕 155ea4ea523fb823bae7ed5fd5235352e1da0936
格式详见文档：[Webhook 支持的请求格式](https://github.com/nfe-w/aio-dynamic-push?tab=readme-ov-file#webhook-%E6%94%AF%E6%8C%81%E7%9A%84%E8%AF%B7%E6%B1%82%E6%A0%BC%E5%BC%8F)
