### ISSUE TITLE
B站的浏览器指纹似乎查不出来了

### ISSUE THREAD

**Issue by Nevak1016** [nfe-w/aio-dynamic-push#15]
我使用登录账号和无痕都尝试获取payload
但是/x/internal/gaia-gateway/ExClimbWuzhi是没有的
![1716175791818](https://github.com/nfe-w/aio-dynamic-push/assets/77886947/2b90588e-565b-4bc0-8a1a-7fe4e5f852bd)

**Comment by nfe-w** [comment]
大概率是改风控策略了😢😢晚些我看看

**Comment by Nevak1016** [comment]
> 大概率是改风控策略了😢😢晚些我看看

我直接填写了cookie里的buvid3，目前是直播间可以成功初始化，但是动态不行，一直是-352

**Comment by Nevak1016** [comment]
> 大概率是改风控策略了😢😢晚些我看看

你好呀，我尝试修改了header，在加入UA和buvid3（通过无痕模式获取到的）后似乎目前稳定获取动态和直播间。
<img width="654" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/77886947/d5e4672c-b49f-4c2e-98e9-34b5da99b556">

**Comment by nfe-w** [comment]
我找到原因了，不是改风控策略了，是在使用 /ExClimbWuzhi 接口激活 buvid3 后，浏览器会reload一下，导致 /ExClimbWuzhi 请求在 Network 记录中看不到。

可以如图，在无痕浏览器的调试模式把网速改为 Slow 3G，然后打开首页，盯住 /ExClimbWuzhi 请求，在发出请求的那一刻，停止记录日志，然后就可以拿到 payload 了🤣
![image](https://github.com/nfe-w/aio-dynamic-push/assets/41944640/5c28a053-fb46-4184-a763-45cc7a4aadd8)

**Comment by nfe-w** [comment]
我找到原因了，不是改风控策略了，是在使用 /ExClimbWuzhi 接口激活 buvid3 后，浏览器会reload一下，导致 /ExClimbWuzhi 请求在 Network 记录中看不到。

可以如图，在无痕浏览器的调试模式把网速改为 Slow 3G，然后打开首页，盯住 /ExClimbWuzhi 请求，在发出请求的那一刻，停止记录日志，然后就可以拿到 payload 了🤣
<img width="1112" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/7d44b994-da0d-4476-b45b-46f0c49ad9b7">

**Comment by muyuanjin** [comment]
把 Preserve log/保留日志  勾上也行

**Comment by nfe-w** [comment]
> 把 Preserve log/保留日志 勾上也行

学到了，这个按钮对于页面会 刷新/重定向 时找日志太方便了👍🏻之前都没注意到
