### ISSUE TITLE
小红书配置初始化后多次请求返回数据为空

### ISSUE THREAD

**Issue by LionYu66** [nfe-w/aio-dynamic-push#17]
stderr: 2024-05-27 19:17:03,733 - 9-MainThread -            config.py[line: 18] -  INFO: 加载配置common: {'proxy_pool': {'enable': 'ture', 'proxy_pool_url': 'http://192.168.100.1:5010'}}
stderr: 2024-05-27 19:17:03,734 - 9-MainThread -             proxy.py[line: 23] -  INFO: 【ip池】已启用，地址: http://192.168.100.1:5010
stderr: 2024-05-27 19:17:03,994 - 9-MainThread -              main.py[line: 12] -  INFO: 开始初始化推送通道
stderr: 2024-05-27 19:17:03,994 - 9-MainThread -              main.py[line: 19] -  INFO: 初始化推送通道: 推送通道_Bark，通道类型: bark
stderr: 2024-05-27 19:17:03,994 - 9-MainThread -              main.py[line: 23] -  INFO: 初始化查询任务
stderr: 2024-05-27 19:17:03,994 - 9-MainThread -              main.py[line: 28] -  INFO: 初始化查询任务: 任务_xhs，任务类型: xhs
stderr: 2024-05-27 19:17:03,998 - 9-MainThread -             proxy.py[line: 41] - ERROR: 【ip池】连接失败
stderr: 2024-05-27 19:17:04,554 - 9-MainThread -         query_xhs.py[line: 79] -  INFO: 【小红书-查询动态状态-任务_xhs】【repboy】动态初始化：deque(['6613ccb0000000001a0114a7', '66194208000000001a017871', '661d01ce000000001a00fe0d', '661e62b6000000000100547d', '662101330000000001030906', '6626319d0000000001005f0a', '6627907e000000000100542e', '6628ce000000000004018d2e', '662b9604000000000100655b', '662e35fe00000000010074cc', '6630f68a000000001e038ae7', '6634c882000000001e032b06', '66360ab6000000001e0312c6', '663cb85c000000001e033d05', '66409034000000001e034719', '66433baa000000001e038d95', '6648a01a00000000140182d7', '664c6dfa00000000160132f9', '664da5c80000000016010842', '66531b630000000016012e75'], maxlen=20)
stderr: 2024-05-27 19:32:19,744 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 19:47:30,012 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 19:47:30,260 - 9-MainThread -         query_xhs.py[line: 52] - ERROR: 【小红书-查询动态状态-任务_xhs】请求返回数据为空，profile_id：61582f8f000000000201da52
stderr: 2024-05-27 20:02:36,465 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 20:17:45,332 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 20:17:45,617 - 9-MainThread -         query_xhs.py[line: 52] - ERROR: 【小红书-查询动态状态-任务_xhs】请求返回数据为空，profile_id：61582f8f000000000201da52
stderr: 2024-05-27 20:32:52,815 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 20:47:58,146 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 20:47:58,436 - 9-MainThread -         query_xhs.py[line: 52] - ERROR: 【小红书-查询动态状态-任务_xhs】请求返回数据为空，profile_id：61582f8f000000000201da52
stderr: 2024-05-27 21:03:03,649 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 21:18:15,808 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 21:33:24,398 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip
stderr: 2024-05-27 21:48:42,795 - 9-MainThread -             proxy.py[line: 64] -  INFO: 【ip池】尝试多次均未获取到有效ip

**Comment by nfe-w** [comment]
其实IP池功能我自己也没怎么用过😢把IP池关上试试呢

**Comment by LionYu66** [comment]
关上了也会出现这个问题，不是很懂哪里配置不正确，抖音的动态和开播提醒开了之后好像初始化也不正常，没有提醒过😭

**Comment by nfe-w** [comment]
抖音的检测确实坏掉了，暂时还不知道怎么修，但其他3个都是好的，我一直在用🧐可以贴一下配置(脱敏后)我明天看看
---- 回复的原邮件 ----
***@***.***>发送日期2024年05月27日 23:10 ***@***.***> ***@***.***>,
***@***.***>主题Re: [nfe-w/aio-dynamic-push] 小红书配置初始化后多次请求返回数据为空 (Issue #17)
关上了也会出现这个问题，不是很懂哪里配置不正确，抖音的动态和开播提醒开了之后好像初始化也不正常，没有提醒过😭

**Comment by nfe-w** [comment]
抖音的检测确实坏掉了，暂时还不知道怎么修，但其他3个都是好的，我一直在用🧐可以贴一下配置(脱敏后)我明天看看​

**Comment by LionYu66** [comment]
common:
  # ip 代理池
  proxy_pool:
    # 是否启用 true/false
    enable: false
    # ip池地址，参考 https://github.com/jhao104/proxy_pool
    proxy_pool_url: http://192.168.100.1:5010

query_task:
  # 任务名称，可自定义
  - name: 任务_bilibili
    # 是否启用 true/false
    enable: false
    # 任务类型，bilibili/weibo/xhs/douyin
    type: bilibili
    # 查询间隔，单位秒，不建议设置太频繁
    intervals_second: 60
    # 查询开始时间，格式 HH:mm
    begin_time: "00:00"
    # 查询结束时间，格式 HH:mm
    end_time: "23:59"
    # 推送通道名称，对应 push_channel 中的 name
    target_push_name_list:
      - 推送通道_企业微信应用
      - 推送通道_钉钉机器人
    # 是否启用动态检测 true/false
    enable_dynamic_check: true
    # 是否启用直播检测 true/false
    enable_living_check: true
    # 用户 uid 列表，参考 https://space.bilibili.com/1795147802
    uid_list:
      - 1795147802
      - 1669777785
      - 1778026586
      - 1875044092
      - 1811071010
      - 2018113152
    # 如果请求提示 -352, 可以填入下面两项之一, 建议使用 payload 自动获取buvid3
    # cookie，可以一定程度防ban，建议用小号的，貌似无痕窗口不登录时拿到的cookie也能用，优先级高于自动获取buvid3
    cookie: ""
    # 浏览器指纹，取自于 /x/internal/gaia-gateway/ExClimbWuzhi 接口的body，需要填入的是payload参数的value，用于自动获取并激活buvid3
    payload: ""
  - name: 任务_weibo
    enable: false
    type: weibo
    intervals_second: 60
    begin_time: "00:00"
    end_time: "23:59"
    target_push_name_list:
      - 推送通道_企业微信应用
      - 推送通道_钉钉机器人
    enable_dynamic_check: true
    # 用户 uid 列表，参考 https://weibo.com/u/7198559139
    uid_list:
      - 7198559139
      - 1765893783
  - name: 任务_xhs
    enable: ture
    type: xhs
    intervals_second: 900
    begin_time: "09:30"
    end_time: "22:00"
    target_push_name_list:
      - 推送通道_Bark
    enable_dynamic_check: true
    # 用户 profile_id 列表，参考 https://www.xiaohongshu.com/user/profile/52d8c541b4c4d60e6c867480
    profile_id_list:
      - 61582f8f000000000201da52
  - name: 任务_douyin
    enable: false
    type: douyin
    intervals_second: 30
    begin_time: "22:00"
    end_time: "01:00"
    target_push_name_list:
      - 推送通道_Bark
    enable_dynamic_check: true
    # 签名服务器url，参考 https://github.com/coder-fly/douyin-signature
    signature_server_url: http://http://192.168.100.1:7878/
    # 用户名列表，必填（接口现在不返回作者信息了，重新获取还挺麻烦的，自己填上凑合用先）
    username_list:
      - 
    # 作者sec_uid列表，参考 https://www.douyin.com/user/MS4wLjABAAAA5ZrIrbgva_HMeHuNn64goOD2XYnk4ItSypgRHlbSh1c
    sec_uid_list:
      - 
    enable_living_check: true
    # 抖音号列表，用于检测开播状态，如果不开启直播检测可以不填，暂不支持纯数字的抖音号
    douyin_id_list:
      - 

push_channel:
  # 通道名称，唯一，可自定义不要纯数字，对应 query_task 中的 target_push_name_list
  - name: 推送通道_Server酱_Turbo
    # 是否启用 true/false
    enable: false
    # 通道类型，serverChan_turbo/wecom_apps/dingtalk_bot/feishu_apps/feishu_bot/bark/webhook
    type: serverChan_turbo
    # Server酱_Turbo推送服务，如果启用该推送，必须填入，获取参考 https://sct.ftqq.com
    send_key:
  - name: 推送通道_企业微信应用
    enable: false
    type: wecom_apps
    # 企业id，如果启动该推送则必填
    corp_id:
    # 应用id，如果启动该推送则必填
    agent_id:
    # 应用Secret，如果启动该推送则必填
    corp_secret:
  - name: 推送通道_企业微信机器人
    enable: false
    type: wecom_bot
    # 机器人key，如果启动该推送则必填
    key:
  - name: 推送通道_钉钉机器人
    enable: false
    type: dingtalk_bot
    # 机器人秘钥，如果启动该推送则必填
    access_token:
  - name: 推送通道_飞书自建应用
    enable: false
    type: feishu_apps
    # 飞书自建应用的app_id，如果启动该推送则必填
    app_id:
    # 飞书自建应用的app_secret，如果启动该推送则必填
    app_secret:
    # 消息接收者id类型 open_id/user_id/union_id/email/chat_id，详见 https://open.feishu.cn/document/server-docs/im-v1/message/create
    receive_id_type:
    # 消息接收者的ID，ID类型应与查询参数receive_id_type 对应
    receive_id:
  - name: 推送通道_飞书机器人
    enable: false
    type: feishu_bot
    # 飞书机器人webhook key，如果启动该推送则必填
    webhook_key:
  - name: 推送通道_Telegram机器人
    enable: false
    type: telegram_bot
    # Telegram 机器人的token，如果启动该推送则必填
    api_token:
    # Telegram 机器人的chat_id，如果启动该推送则必填，详见 https://api.telegram.org/bot<YOUR_API_TOKEN>/getUpdates
    chat_id:
  - name: 推送通道_Bark
    enable: ture
    type: bark
    # iOS 设备专用，Bark app 的key，如果启动该推送则必填
    key: 
  - name: 推送通道_Gotify
    enable: false
    type: gotify
    # Gotify 服务器地址，如果启动该推送则必填，例如 https://push.example.com/message?token=<apptoken>
    web_server_url:
  - name: 推送通道_Webhook
    enable: false
    type: webhook
    # Webhook 地址，如果启动该推送则必填，标题和内容使用 {{title}} 和 {{content}} 占位符
    webhook_url: https://xxx.com?title={{title}}&content={{content}}
    # 请求方法，GET/POST
    request_method: GET
  - name: 推送通道_Email
    enable: false
    type: email
    # SMTP 服务器地址，如果启动该推送则必填，例如 smtp.qq.com
    smtp_host:
    # SMTP 服务器端口，如果启动该推送则必填，例如 465
    smtp_port:
    # 是否启用SSL，默认true
    smtp_ssl: true
    # 是否启用TSL，默认false
    smtp_tls: false
    # 发件人邮箱，如果启动该推送则必填
    sender_email:
    # 发件人密码，如果启动该推送则必填，QQ邮箱需要使用授权码，参考 https://service.mail.qq.com/detail/0/75
    sender_password:
    # 收件人地址，如果启动该推送则必填，多个地址用英文逗号分隔
    receiver_email:

**Comment by nfe-w** [comment]
我试了一下，是可以正常查询的，是不是你的网络环境问题呢，可以更换一个网络试试看

此外，你的配置中，`true`拼成`ture `了
<img width="1689" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/17c1a2ea-e747-439d-95d6-c3ca1236fc21">

**Comment by LionYu66** [comment]
感谢指正，犯低级错误了🥲，我再尝试一下
