### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by u2shana** [nfe-w/aio-dynamic-push#19]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/14146754/eb1fbeb2-3a2f-4bb1-914f-6b09a4ba845f)
因为docker版本不支持arm架构，只能代码执行，但是拉完依赖后启动报错

**Comment by u2shana** [comment]
没事了，代码运行错误是直接copy github文字导致的莫名其妙语法问题

**Comment by nfe-w** [comment]
已添加arm64的镜像支持，可以试试docker了

**Comment by u2shana** [comment]
> 已添加arm64的镜像支持，可以试试docker了

已测试，arm64的docker版本正常运行
