### ISSUE TITLE
【虎牙】我配置了推送通道，但是没有收到通知

### ISSUE THREAD

**Issue by wwkk2580** [nfe-w/aio-dynamic-push#22]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/666c11c8-cda2-4199-a690-be886eabde07)

![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/5cfe7b6f-8b30-48d2-9525-304ce2bb09dd)

**Comment by nfe-w** [comment]
对于钉钉群机器人，给机器人如图设置关键字"【"再试试
<img width="634" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/5de8103c-3fd3-4ff7-b501-18b267a363bf">

**Comment by wwkk2580** [comment]
> 对于钉钉群机器人，给机器人如图设置关键字"【"再试试 <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/41944640/343185169-5de8103c-3fd3-4ff7-b501-18b267a363bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTQyOTYsIm5iZiI6MTcxOTQ1Mzk5NiwicGF0aCI6Ii80MTk0NDY0MC8zNDMxODUxNjktNWRlODEwM2MtM2ZkMy00ZmY3LWI1MDEtMThiMjY3YTM2M2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAyMDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGE4ODNhMTk0YTJkNzU1NjQxNmQyODMzMjUwNmIxOTQ5OTVkYTBmMjA0MmIxNmE3MzY2MGQwZmViMzI5NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n5NjBr7KsE5WFdb3mcZzWodp8LN70dWLiG34G0Cu6sc">

![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/8ce8ec28-3e4f-4f5a-b9fc-8b9f81d71441)
邮件方式也没有通知

**Comment by nfe-w** [comment]
钉钉机器人配置了【还是不行吗？

**Comment by wwkk2580** [comment]
我的环境是虚拟机的docker，是不是跟这个有关？邮件也没有

**Comment by nfe-w** [comment]
我也是linux下的docker部署的，你在命令行这样试试，看看是不是网络环境的事儿：
```sh
curl --location --request POST 'https://oapi.dingtalk.com/robot/send?access_token=这里写你的秘钥' --header 'Content-Type: application/json' --data-raw '{ "msgtype": "link", "link": { "title": "测试标题", "text": "测试内容", "messageUrl": "https://www.baidu.com" } }'
```

**Comment by wwkk2580** [comment]
好奇怪啊，可用
![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/102a370d-a849-4f48-844f-a3dca35f4fb9)

**Comment by wwkk2580** [comment]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/fcf65918-40e1-45b8-ac0d-7c0f85854a06)
是不是这个的问题

**Comment by wwkk2580** [comment]
找到原因了
![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/4be4339c-015e-4911-afca-56f0438bf343)
这里增加点文字就可以了，好像是钉钉对链接信息的处理有问题
![image](https://github.com/nfe-w/aio-dynamic-push/assets/76099203/97d530db-57ae-49d5-aaf6-22cbbcb3892b)

**Comment by nfe-w** [comment]
感谢定位问题，已修复，重新拉镜像即可。

估计是你检测的这个直播间没标题，不知道为啥会出现这种情况，我之前自测的时候没遇到过
