### ISSUE TITLE
小红书的直播检测后续会有支持吗？

### ISSUE THREAD

**Issue by winniesi** [nfe-w/aio-dynamic-push#28]
不了解小红书的机制，是否很难检测直播？

**Comment by nfe-w** [comment]
过几天看一下，之前我不知道小红书也有直播功能😂

**Comment by nfe-w** [comment]
我看了一下web端，好像没找到直播相关的标识字段，估计是不太好做，小红书的直播像是app专属功能，对于这种估计是比较难检测到
