### ISSUE TITLE
请教下浏览器指纹payload要如何获取

### ISSUE THREAD

**Issue by cnscj** [nfe-w/aio-dynamic-push#3]

**Comment by nfe-w** [comment]
如图，在浏览器的无痕模式的F12内
![iShot_2024-04-10_18 26 02](https://github.com/nfe-w/aio-dynamic-push/assets/41944640/54908cc0-ed28-48b4-81d1-ff4246ca82bf)

**Comment by cnscj** [comment]
> 如图，在浏览器的无痕模式的F12内 ![iShot_2024-04-10_18 26 02](https://private-user-images.githubusercontent.com/41944640/321197762-54908cc0-ed28-48b4-81d1-ff4246ca82bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDg5MTksIm5iZiI6MTcxMjc0ODYxOSwicGF0aCI6Ii80MTk0NDY0MC8zMjExOTc3NjItNTQ5MDhjYzAtZWQyOC00OGI0LTgxZDEtZmY0MjQ2Y2E4MmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDExMzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjk3Y2Y1NjMxOGU1ZDQyNGM1Y2ExOWJkNWFkNmFkOWJiZGI3N2JjODFkMzBiODQ2OGI2ZmYxMWE1MjJhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7sWG7OINB0RxlcX6EKoAxpA4_MBRfIhyzTGw2KVC2h4)

貌似现在必须登录账号才能拿到
