### ISSUE TITLE
b站动态推送

### ISSUE THREAD

**Issue by candybits** [nfe-w/aio-dynamic-push#31]
配置内能否增加一个开关，可以自由选择转发类动态推送的开启与关闭？

**Comment by nfe-w** [comment]
已添加，详见 https://github.com/nfe-w/aio-dynamic-push/blob/master/config.yml#L43

**Comment by u2shana** [comment]
动态有更新，但不在需要推送的动态类型列表中，dynamic_type->DYNAMIC_TYPE_LIVE_RCMD
貌似新增了一种动态类型，但是我看和普通带图片的动态一样，很怪

**Comment by nfe-w** [comment]
> 动态有更新，但不在需要推送的动态类型列表中，dynamic_type->DYNAMIC_TYPE_LIVE_RCMD 貌似新增了一种动态类型，但是我看和普通带图片的动态一样，很怪

请提供一条动态样例，我分析看看

**Comment by u2shana** [comment]
> > 动态有更新，但不在需要推送的动态类型列表中，dynamic_type->DYNAMIC_TYPE_LIVE_RCMD 貌似新增了一种动态类型，但是我看和普通带图片的动态一样，很怪
> 
> 请提供一条动态样例，我分析看看

我明白了，这个是直播时的系统推送动态，确实可以无视掉。不过我刚才是因为遇到了一条动态没推送，所以才去看日志的，日志什么都没打印

**Comment by u2shana** [comment]
> 动态有更新，但不在需要推送的动态类型列表中，dynamic_type->DYNAMIC_TYPE_LIVE_RCMD 貌似新增了一种动态类型，但是我看和普通带图片的动态一样，很怪

发现漏了个类型，DYNAMIC_TYPE_COMMON_SQUARE，是佩戴装扮时转发到动态生成的

**Comment by nfe-w** [comment]
需要提供一个例子，我分析下

**Comment by u2shana** [comment]
> 需要提供一个例子，我分析下

自己随便换个装扮，勾选转发到动态就行了

**Comment by u2shana** [comment]
> 需要提供一个例子，我分析下
比如这条https://t.bilibili.com/940624793302990898?tab=2 这种带有一个跳转窗口的链接

**Comment by nfe-w** [comment]
提交&构建了，重新拉镜像试下 1b7cc10dfb302dc753bdedfaa6a687246edd55c5
