### ISSUE TITLE
是否可以通过直播间号检测抖音开播呢？

### ISSUE THREAD

**Issue by xiaocainiao2020** [nfe-w/aio-dynamic-push#4]
请问大佬，如果只想用来监测开播提醒，看到配置文件里的提示说不支持存纯数字的抖音号，那这种纯数字的抖音号直播有什么解决办法吗，能否通过直播间号来监测呢？

**Comment by nfe-w** [comment]
暂时好像做不到，抖音的反爬比较厉害，我对这块儿了解的不多，甚至好像抖音动态检测的接口也挂了我还不知道怎么修复😢

**Comment by xiaocainiao2020** [comment]
> 暂时好像做不到，抖音的反爬比较厉害，我对这块儿了解的不多，甚至好像抖音动态检测的接口也挂了我还不知道怎么修复😢

https://www.52pojie.cn/thread-1808116-1-1.html
作者大大可以看下这个帖子，提供了一种方便的检测开播状态的方法。我用check酱1分钟检测一次，用了挺久了ip没有被禁。

**Comment by nfe-w** [comment]
好的谢谢， 稍晚些我看看

**Comment by nfe-w** [comment]
已实现，现在配置中的`douyin_id_list`支持纯数字抖音号了🎉
