### ISSUE TITLE
有两个error

### ISSUE THREAD

**Issue by Draudnaut** [nfe-w/aio-dynamic-push#5]
![image](https://github.com/nfe-w/aio-dynamic-push/assets/16780642/c50c7ddf-eaba-4aaa-a5f2-3f19df3c90c3)

po主能帮忙看下这两个error的可能来源么，有一个是越界还有一个是动态列表为空

**Comment by nfe-w** [comment]
想问下你是只配置了 2 个 uid 吗？一个 7484247626，另一个 6279793937

如果只有这 2 个 uid 的话，那这 2 个 error 都是来自于 7484247626：

1. 动态列表为空这个是偶发的触发反爬，不太影响使用
2. 越界我看了下是在取 cards[0] 时报错了，猜测可能是把置顶微博跳过后列表就空了（其实感觉反爬或网络环境的原因，我看了下这个账号是很多条微博），兼容修复了一下：  c0882b948e853ec23d7d902e98d94c150961001a

**Comment by nfe-w** [comment]
镜像构建完毕了，可以再拉下镜像试试看

**Comment by Draudnaut** [comment]
okok，我至少监控了六个（

**Comment by Draudnaut** [comment]
感谢po主！

NFE_W ***@***.***> 于2024年4月27日周六 12:36写道：
