### ISSUE TITLE
wecom_bot通知展现，description、picurl 缺失

### ISSUE THREAD

**Issue by Looper0331** [nfe-w/aio-dynamic-push#8]
![微信截图_20240507103534](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/ffd3b150-7eb5-42c5-ba47-f10f43ad4eef)

**Comment by nfe-w** [comment]
好的，下班后我试一下

**Comment by Looper0331** [comment]
> 好的，下班后我试一下

好的，麻烦了~感谢~

**Comment by nfe-w** [comment]
目前小红书只展示标题（其实就是把标题当做描述了），[]其实是时间我晚些看看当时为啥没加上，图片的这块我试了下倒是可以的
<img width="1376" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/9df7842f-fec0-45a1-b8c1-a2caca9909f2">

**Comment by nfe-w** [comment]
3cc26b0962831c1393d480de1cc43ec8ba8ecf97 完善了一下推送的内容和动态发布时间，重新拉镜像试试看效果

**Comment by nfe-w** [comment]
<img width="319" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/96d86539-c292-438b-b778-80362cb7fbfc">

**Comment by Looper0331** [comment]
> <img width="319" alt="image" src="https://github.com/nfe-w/aio-dynamic-push/assets/41944640/96d86539-c292-438b-b778-80362cb7fbfc">
> 
> 

好的，我一会到家了试试看，感谢感谢🙏

**Comment by Looper0331** [comment]
> 目前小红书只展示标题（其实就是把标题当做描述了），[]其实是时间我晚些看看当时为啥没加上，图片的这块我试了下倒是可以的 <img alt="image" width="1376" src="https://private-user-images.githubusercontent.com/41944640/328371759-9df7842f-fec0-45a1-b8c1-a2caca9909f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTczNzksIm5iZiI6MTcxNTA5NzA3OSwicGF0aCI6Ii80MTk0NDY0MC8zMjgzNzE3NTktOWRmNzg0MmYtZmVjMC00NWExLWI4YzEtYTJjYWNhOTkwOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE1NTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjM1ZDA1YTQ1ZTJmYjJmODZmMzEzZWQwNTA2ZDg0MjA4ZTExMzlkYTE4YzM3MGY5YmYwYTljYmIyMzBmMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i0El6AaRk9RhDZq3VX7qmERBhCmdisTRqf3nUkHiX0M">

![image](https://github.com/nfe-w/aio-dynamic-push/assets/66026703/4e08f5b1-47d0-4925-b121-13c45fca73fd)
发现一个很奇怪的情况，电脑上不展示图片，手机端却可以看到，电脑和手机都是同一WiFi下。。。
