### ISSUE TITLE
B站获取动态一直-352

### ISSUE THREAD

**Issue by Arukassss** [nfe-w/aio-dynamic-push#9]
试过填cookie和payload，都是刚启动的时候获取成功，第二次获取的时候就一直-352了，间隔60秒

**Comment by nfe-w** [comment]
不填写cookie，只填写payload试试看，payload可以在无痕模式重新获取一个新的

**Comment by Arukassss** [comment]
> 不填写cookie，只填写payload试试看，payload可以在无痕模式重新获取一个新的

都试过了，单cookie单payload 两个一起填都试过了，现在把间隔放到120秒暂时没有报错

**Comment by Arukassss** [comment]
> > 不填写cookie，只填写payload试试看，payload可以在无痕模式重新获取一个新的
> 
> 都试过了，单cookie单payload 两个一起填都试过了，现在把间隔放到120秒暂时没有报错

单cookie

**Comment by nfe-w** [comment]
我是10分钟内约28个请求，是正常的，先观察看看
